# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - analytics-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fastapianalyticsserver.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4c6c0c7fd6f8401ba9f7d0f2b30fa36c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4d9ee200141e40f3ac646f1adeb1e212 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fastapianalyticsserver.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4c6c0c7fd6f8401ba9f7d0f2b30fa36c }}/fastapianalyticsserver/analyticsserver:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'analytics-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_40bbcef71842455fbfc58ee491710de6 }}
        images: 'fastapianalyticsserver.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4c6c0c7fd6f8401ba9f7d0f2b30fa36c }}/fastapianalyticsserver/analyticsserver:${{ github.sha }}'